#ifndef KHOROS_GFX_GPU_MATH_H
#define KHOROS_GFX_GPU_MATH_H

#if __STDC_VERSION__ < 202311L
#error "Khoros requires pure ISO C23 (compile with -std=c23)"
#endif

#ifdef _STDBOOL_H
#error "<stdbool.h> is strictly banned. In C23, bool, true, and false are native language keywords."
#endif

#ifdef _STDALIGN_H
#error "<stdalign.h> is strictly banned. In C23, alignas and alignof are native language keywords."
#endif

#include <stdint.h>
#include <vulkan/vulkan.h>
#include "khoros/core/attributes.h"

/*
 * Column-major 4x4 matrix matching Slang Mat4 and SPIR-V 1.6 column vectors.
 * Stored as 4 columns of 4 floats (64 bytes).
 */
typedef struct {
    alignas(16) float c0[4];
    float c1[4];
    float c2[4];
    float c3[4];
} khr_gpu_mat4_t;

/*
 * GPU Instance Data descriptor passed to cull.slang compute shader via BDA.
 * 80 bytes, 16-byte aligned.
 */
typedef struct {
    alignas(16) float position[3];  /* World space translation */
    float    radius;                /* Local bounding sphere radius */
    float    rotation[4];           /* Unit Quaternion (x, y, z, w) */
    float    scale[3];              /* Non-uniform scale */
    uint32_t mesh_id;               /* Mesh selector / user data */
    alignas(16) float albedo[3];    /* Surface diffuse base color */
    float    roughness;             /* Microfacet roughness [0.045, 1.0] */
    float    metallic;              /* Metallicness [0.0 = dielectric, 1.0 = metal] */
    float    ao;                    /* Ambient occlusion factor [0.0, 1.0] */
    uint32_t albedo_tex_id;         /* Bindless texture heap index (or UINT32_MAX for untextured) */
    uint32_t normal_tex_id;         /* Bindless normal map heap index (or UINT32_MAX for flat) */
} khr_gpu_instance_t;

/*
 * GPU Culled Instance Output generated by cull.slang via BDA.
 * 192 bytes, 16-byte aligned.
 */
typedef struct {
    alignas(16) khr_gpu_mat4_t mvp;    /* Pre-multiplied View-Projection * Model */
    khr_gpu_mat4_t model;              /* World Transform Model matrix */
    alignas(16) float rotation[4];     /* Unit Quaternion (x, y, z, w) */
    float    scale[3];                 /* Non-uniform scale */
    float    pad0;                     /* Padding to 16-byte boundary */
    alignas(16) float albedo[3];       /* Surface diffuse base color */
    float    roughness;                /* Microfacet roughness */
    float    metallic;                 /* Metallicness */
    float    ao;                       /* Ambient occlusion factor */
    uint32_t albedo_tex_id;            /* Bindless texture heap index (or UINT32_MAX for untextured) */
    uint32_t normal_tex_id;            /* Bindless normal map heap index (or UINT32_MAX for flat) */
} khr_gpu_culled_instance_t;

/*
 * Vulkan Draw Indirect Command matching hardware specification (VkDrawIndirectCommand).
 * 16 bytes.
 */
typedef struct {
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
} khr_draw_indirect_cmd_t;

/*
 * Vulkan Draw Indexed Indirect Command matching hardware specification (VkDrawIndexedIndirectCommand).
 * 20 bytes.
 */
typedef struct {
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    int32_t  vertexOffset;
    uint32_t firstInstance;
} khr_draw_indexed_indirect_cmd_t;

/*
 * Push constant layout for cull.slang compute shader.
 * Total size: 96 bytes (<= 128 byte Vulkan hardware guarantee).
 * Vector fields packed into float4 to guarantee exact 16-byte alignment match between C and SPIR-V.
 */
typedef struct {
    alignas(8) VkDeviceAddress instances_addr;        /* BDA: const khr_gpu_instance_t* */
    VkDeviceAddress culled_instances_addr;            /* BDA: khr_gpu_culled_instance_t* */
    VkDeviceAddress draw_cmd_addr;                    /* BDA: khr_draw_indirect_cmd_t* */
    VkDeviceAddress draw_count_addr;                  /* BDA: uint32_t* (optional atomic count) */
    uint32_t        instance_count;                   /* offset 32 */
    uint32_t        index_count;                      /* offset 36 */
    union {
        uint32_t    pad0;                             /* offset 40 */
        float       alpha;                            /* render time alpha for tick interpolation */
    };
    union {
        uint32_t    pad1;                             /* offset 44 */
        uint32_t    flags;                            /* bit 0: interpolate, bit 1: prev_slot */
    };
    alignas(16) float eye_fov[4];                     /* offset 48: eye.xyz, w = fov_y */
    alignas(16) float target_aspect[4];               /* offset 64: target.xyz, w = aspect */
    alignas(16) float up_znear[4];                    /* offset 80: up.xyz, w = z_near */
} khr_cull_push_t;

/*
 * Light Type enumeration.
 */
typedef enum {
    KHR_LIGHT_DIRECTIONAL = 0,
    KHR_LIGHT_POINT       = 1,
    KHR_LIGHT_SPOT        = 2,
} khr_light_type_t;

/*
 * GPU Light Descriptor matching SPIR-V STD430 layout.
 * 64 bytes, 16-byte aligned.
 */
typedef struct {
    alignas(16) float position[3]; /* World position (Point/Spot) */
    uint32_t type;                 /* 0 = Directional, 1 = Point, 2 = Spot */
    alignas(16) float direction[3];/* Normalized direction vector (Directional/Spot) */
    float    range;                /* Effective attenuation radius R in meters */
    alignas(16) float color[3];    /* Linear RGB color / spectral tint */
    float    intensity;            /* Luminous intensity (cd) or illuminance (lx) */
    alignas(16) float spot_inner;  /* Cosine of inner cone half-angle (e.g. cos(20 deg)) */
    float    spot_outer;           /* Cosine of outer cone half-angle (e.g. cos(35 deg)) */
    float    pad[2];               /* Padding to 64 bytes */
} khr_gpu_light_t;

/*
 * Push constant layout for mesh_instanced.slang vertex/fragment shader.
 * Total size: 112 bytes (<= 128 byte Vulkan hardware guarantee).
 */
typedef struct {
    alignas(8) VkDeviceAddress instances_addr;   /* BDA: const khr_gpu_culled_instance_t* */
    VkDeviceAddress verts_addr;                  /* BDA: const float* (packed xyz) */
    VkDeviceAddress indices_addr;                /* BDA: const uint32_t* */
    VkDeviceAddress lights_addr;                 /* BDA: const khr_gpu_light_t* (offset 24) */
    alignas(16) float light_dir[4];              /* offset 32: fallback dir.xyz, w = intensity */
    alignas(16) float camera_pos[4];             /* offset 48: xyz = eye pos, w = unused */
    alignas(16) float light_color[4];            /* offset 64: rgb = color, w = ambient level */
    uint32_t        index_count;                 /* offset 80 */
    uint32_t        vert_count;                  /* offset 84 */
    uint32_t        light_count;                 /* offset 88: number of active lights */
    uint32_t        target_mesh_id;              /* offset 92: filter by mesh id (UINT32_MAX = all) */
    VkDeviceAddress normals_addr;                /* offset 96: BDA: const float* (packed normal xyz) */
    uint32_t        pad2[2];                     /* offset 104: total 112 bytes */
} khr_mesh_instanced_push_t;

static_assert(sizeof(khr_gpu_mat4_t) == 64, "Mat4 size must be 64 bytes");
static_assert(sizeof(khr_gpu_instance_t) == 80, "Instance size must be 80 bytes");
static_assert(sizeof(khr_gpu_culled_instance_t) == 192, "CulledInstance size must be 192 bytes");
static_assert(sizeof(khr_gpu_light_t) == 64, "Light size must be 64 bytes");
static_assert(sizeof(khr_draw_indirect_cmd_t) == 16, "IndirectCmd size must be 16 bytes");
static_assert(sizeof(khr_draw_indexed_indirect_cmd_t) == 20, "IndexedIndirectCmd size must be 20 bytes");
static_assert(sizeof(khr_cull_push_t) == 96, "CullPush size must be 96 bytes");
static_assert(sizeof(khr_mesh_instanced_push_t) == 112, "MeshInstancedPush size must be 112 bytes");
static_assert(sizeof(khr_cull_push_t) <= 128, "CullPush must fit within 128 bytes");
static_assert(sizeof(khr_mesh_instanced_push_t) <= 128, "MeshInstancedPush must fit within 128 bytes");
static_assert(alignof(khr_gpu_light_t) == 16, "Light alignment must be 16 bytes");
static_assert(offsetof(khr_cull_push_t, eye_fov) == 48, "eye_fov offset must be 48");
static_assert(offsetof(khr_cull_push_t, target_aspect) == 64, "target_aspect offset must be 64");
static_assert(offsetof(khr_cull_push_t, up_znear) == 80, "up_znear offset must be 80");
static_assert(offsetof(khr_mesh_instanced_push_t, lights_addr) == 24, "lights_addr offset must be 24");
static_assert(offsetof(khr_mesh_instanced_push_t, light_dir) == 32, "light_dir offset must be 32");
static_assert(offsetof(khr_mesh_instanced_push_t, camera_pos) == 48, "camera_pos offset must be 48");
static_assert(offsetof(khr_mesh_instanced_push_t, light_color) == 64, "light_color offset must be 64");
static_assert(offsetof(khr_mesh_instanced_push_t, light_count) == 88, "light_count offset must be 88");
static_assert(offsetof(khr_mesh_instanced_push_t, normals_addr) == 96, "normals_addr offset must be 96");

#endif /* KHOROS_GFX_GPU_MATH_H */
